version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-buku_tamu}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-buku_tamu_pass}
      POSTGRES_DB: ${POSTGRES_DB:-buku_tamu}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buku_tamu"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bt-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: bt-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-buku_tamu}:${POSTGRES_PASSWORD:-buku_tamu_pass}@postgres:5432/${POSTGRES_DB:-buku_tamu}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      TZ: Asia/Jakarta

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    container_name: bt-web
    restart: unless-stopped
    depends_on:
      - api

  proxy:
    image: nginx:alpine
    container_name: bt-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api

volumes:
  postgres_data:
  redis_data: