events {}

http {
upstream web { server web:5173; }
upstream api { server api:3000; }

server {
listen 80;
server_name _;

location /api/ {
proxy_pass http://api/;
proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
proxy_set_header X-Real-IP ;
}

location / {
proxy_pass http://web/;
proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
}
}
}
